version: "3.8"

services:
    localstack:
        image: localstack/localstack-light:latest
        ports:
            - "4566:4566"
        environment: 
            SERVICES: dynamodb,s3,lambda,sqs,sts,cloudwatch,iam,cloudformation
            DEBUG: 1